[package]
name = "tests-readme"
description = "Tests for README.md"
version = "0.0.0"
edition = "2018"

[dependencies]
carapax = { path = "../carapax", features = ["access", "i18n", "ratelimit", "session-fs"] }
tempfile = "3.1"
tokio = { version = "0.2", features = ["macros"] }

[workspace]
